version: '3'
services:
  main:
    container_name: main
    build: .
    volumes:
      - .:/app
      - logs:/app/logs/

    ports:
      - ${PORT}:${PORT}
    command: npm run start
    depends_on:
      - postgres
    restart: on-failure
    networks:
      - user-defined-bridge
  postgres:
    container_name: postgres
    build: ./db/.
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db:/var/lib/postgresql/data/
    restart: on-failure
    networks:
      - user-defined-bridge

volumes:
  logs:
  db:

networks:
  user-defined-bridge:
    driver: bridge
