version: '3'
services:
  main:
    container_name: main
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - 4000:4000
      - 9229:9229
    command: npm run start
    depends_on:
      - postgres
    restart: always
    networks:
      - user-defined-bridge
  postgres:
    container_name: postgres
    build: ./db/.
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data/

    restart: always
    networks:
      - user-defined-bridge
volumes:
  pgdata:

networks:
  user-defined-bridge:
    driver: bridge