version: '3'
services:
  main:
    container_name: main
    build: .
    volumes:
      - .:/app
      - logs:/app/logs/

    ports:
      - "4000:4000"
    command: npm run start
    depends_on:
      - postgres
    restart: on-failure
    networks:
      - user-defined-bridge
  postgres:
    container_name: postgres
    build: ./db/.
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "nodejs2021Q4Service"
    volumes:
      - db:/var/lib/postgresql/data/
    restart: on-failure
    networks:
      - user-defined-bridge

volumes:
  logs:
  db:

networks:
  user-defined-bridge:
    driver: bridge
