version: '3'
services:
  main:
    container_name: main
    image: alexgorus/rs:last
    volumes:
      - logs/:/app/logs
      - .:/app
    ports:
      - ${PORT}:${PORT}
    command: npm run start
    depends_on:
      - postgres
    restart: always
    networks:
      - user-defined-bridge
  postgres:
    container_name: postgres
    image: postgres:14-alpine
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db/:/var/lib/postgresql/data/
    restart: always
    networks:
      - user-defined-bridge

volumes:
  logs:
  db:

networks:
  user-defined-bridge:
    driver: bridge